application: web592group13
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
 
- url: /(.*\.(js|css|html|gif|png|jpg|wav|mp3|json))$
  static_files: \1
  upload: .*\.(js|css|html|gif|png|jpg|wav|mp3|json)$
 
- url: /(.*\.php)$
  script: \1
  
- url: .*
  script: main.php